### ISSUE TITLE
Embedded service URL different from server URL

### ISSUE THREAD

**Issue by mkarlesky** [Synergetic-Engineering/odata-influxdb#15]
I think I found a little glitch in using the project when deployed in complex networking environments (e.g. virtual machine hosts/guests, Docker containers, NAT port forwarding, etc.).

In such environments I was able to access the base OData feed but not the entities within. I changed the code such that the URL embedded in the served XML is now configurable. I added an entry `service_advertise_root` in the `[server]` section of the configuration file and modified server.py:

```
def configure_app(c, doc):
    service_root = c.get('server', 'service_advertise_root')
    logger.info("Advertising service at %s" % service_root)
    app = ReadOnlyServer(serviceRoot=service_root)
    app.SetModel(doc)
    return app
```

Once I did the above, I was able to access our data with OData dev tools (e.g. [Sesame](http://metasapiens.com/sesame/data-browser/preview)) and ultimately able to connect up Power BI with our production system. In our usage Influx and odata-influxdb are both running in Docker containers with NAT port forwarding to the host machine.

**Comment by srp-synengco** [comment]
thanks for this one too @mkarlesky  :+1: - reckon you could double check my additions works for your situation?

**Comment by mkarlesky** [comment]
Thanks for putting in the effort to figure out a proper conditional for the new option. However, there are syntax errors in `configure_app()` (two mismatched parens). In addition, I also found that the new `start_server()` is no longer configurable but hardcoded for localhost:8080.

I would have submitted a pull request for the fixes, but I was not able to get my server to start up reliably with the new werkzeug wrapper approach. Anything other than localhost yielded socket errors about an address already being in use. In the end I grabbed the few lines of the new conditional code, corrected the syntax issues, and kept on using our modified version of a previous commit.

Incidentally, you may want to update `get_sample_config()` with a comment for the new configuration option.

Thanks again for the project. Saved us a ton of effort.

p.s. Related to configuration options… we found the [envtpl](https://pypi.python.org/pypi/envtpl) templating tool to be great for building production.conf from configurable environment variables in our Docker container. Thought you might like to know how your project has been deployed by one of its users.

**Comment by srp-synengco** [comment]
Ah, yeah whoops, got my wires crossed on the version i was testing and didn't consider the new way it's going to be done to have auth. thinking i'll wait till we figure that out properly first then get to this

**Comment by soundstripe** [comment]
I think in my development of the auth feature I removed the previous code that was parsing the service_root config option. I like your option name, `service_advertise_root`, but I think it is synonymous with the previous `service_root` option so I'm going to clean that up.
