### ISSUE TITLE
Not seeing Grouping statements in Influx queries

### ISSUE THREAD

**Issue by mkarlesky** [Synergetic-Engineering/odata-influxdb#20]
Hello again.

We've been attempting to use the recently added Grouping features, but we're not having any luck. It appears the requests are essentially ignored.

Here's one of our queries constructed per the example in the documentation:
>`/db__WaterTemperature?$filter=timestamp%20gt%20datetime%272017-06-28T15:57:06%27&$top=1000&groupByTime=5m&aggregate=mean&influxgroupby=*`

The above processes without error but produces a list of all data points with their raw timestamps and no resampling of the data. We _think_ we're constructing the URL properly.

In the logs for odata-influxdb, we see the full query URL come through. However, we don't see any grouping or averaging statements in the resulting Influx query. Below is a log entry produced by the above URL. It appears to be missing the `GROUP BY` and `SELECT mean(*)` Influx query terms.
>Querying InfluxDB: SELECT * FROM "WaterTemperature" WHERE time > '2017-06-28 15:57:06'   LIMIT 1000
##.###.##.### - - [28/Jun/2017 16:57:09] "GET /db__WaterTemperature?$filter=timestamp%20gt%20datetime%272017-06-28T15:57:06%27&$top=1000&groupByTime=5m&aggregate=mean&influxgroupby=* HTTP/1.1" 200 -

Are we overlooking something? To our knowledge, save for a documentation update on June 6, we're using the latest and greatest version of odata-influxdb. Any thoughts appreciated.

**Comment by srp-synengco** [comment]
Hi Mike,

Hmm, that does seem strange, I've tried to replicate it on my machine with our influxdb and it was able to make the `GROUP BY` part of the query. i.e. when I hit `/db__measure?$filter=timestamp%20gt%20datetime%272017-01-01T00:00:00%27&groupByTime=5m&influxgroupby=*` it logs

> INFO:werkzeug:127.0.0.1 - - [30/Jun/2017 14:49:18] "GET /db__measure?filter=timestamp%20gt%20datetime%272017-01-01T00:00:00%27&groupByTime=5m&influxgroupby=* HTTP/1.1" 500 -
> Querying InfluxDB: SELECT COUNT(*) FROM "origin_reheat_flow" WHERE time > '2017-01-01 00:00:00' GROUP BY *,time(5m)

Can i suggest putting in some print statements in the `_groupby_expressions` method on `InfluxDBMeasurement` to see what isn't satisfying the conditions to make it work?

**Comment by mkarlesky** [comment]
It appears that the following `if` statement always evaluates as true.

`
if len(group_by) == 0:
   return ''
`

**Comment by soundstripe** [comment]
Try setting `auth_required` in your config. Even if it's not actually required. Your server may ask for http basic auth but will accept any username/password. 

Right now the custom influx query string options only work if auth is enabled for odata-influxdb.

**Comment by mkarlesky** [comment]
Ah ha. I'll play with configuring that in our setup and let you know. Thanks!

**Comment by mkarlesky** [comment]
Enabling authentication did fix our issue. It just took a bit of finagling to get our specific proxy setup to work along with it. Thanks!
