### ISSUE TITLE
All fields across all measurements advertised for each measurement?

### ISSUE THREAD

**Issue by mkarlesky** [Synergetic-Engineering/odata-influxdb#21]
After expanding our measurements recently, we've noticed a seeming oddity. If measurement Alpha has fields 'foo' and 'bar' while measurement Beta has fields 'bar' and 'baz', then the OData feed includes fields 'foo', 'bar', and 'baz' for both Alpha and Beta. Is this expected?

**Comment by srp-synengco** [comment]
yeah, that is my understanding of how it builds the metadata, not trying to be too smart i believe, for simplicity's sake

haven't tested whether it has any major effects on query performance, it does send a bit of a bum steer, but for our purposes so far it's obvious what's what so hasn't really gotten in the way (in our use case the vast majority of measures share a very similar set of tag keys)

**Comment by mkarlesky** [comment]
Thanks for the clarification and confirmation.
