### ISSUE TITLE
Any Python3 supports for this project in the future?

### ISSUE THREAD

**Issue by Zhenye-Na** [Synergetic-Engineering/odata-influxdb#26]
Hi Developing Team,

This is Zion here, I came across this great project and found out this is super suitable for our usage. However, I am using Python3 so I am wondering will there be future support for Python3 version? Even though I have already figured out the Python3 version code from my side with only 1 testcase failed. So far so good.

Or I can make a pull request to create a new branch like `py3_version`, for other people's convenience?

Anyway, thank you for your time and contribution!

Best regards,
Zion

**Comment by soundstripe** [comment]
I'm no longer working on this project but at the time it began, some of the upstream packages were not working well with Python3. That has changed and it would likely work at least with 3.3 (pyslet specifies 3.3 support), possibly higher.

**Comment by Zhenye-Na** [comment]
Hi Steven @soundstripe

I have successfully figured out transform this project to Python3. Does this project support long-term connection with InfluxDB? Suppose I have my OData server running and I have written some new data points to the InfluxDB instance. Does the OData server "update" data automatically or I should manually restart the service?

**Comment by soundstripe** [comment]
New data will flow through the service, but data structure changes will require reconfiguration.

**Comment by Zhenye-Na** [comment]
As for the KeyError of boolean error, I commented on another issue, I successfully resolved it by ignoring the other DBs. Now it is working!

Thanks!
