### ISSUE TITLE
Reflect nested structure of influx database -> measurement

### ISSUE THREAD

**Issue by srp-synengco** [Synergetic-Engineering/odata-influxdb#4]
at the moment, to get the thing working the influx databases and measurements have been flattened into single resources from the odata api perspective

It'd be great if we could separate these out as nested resources to better reflect how influx is structured

**Comment by soundstripe** [comment]
I've explored a variety of way to do this, and I can't find one that would be effective. At some point an EntityType in OData must correspond to each type of measurement in InfluxDB, and so making a hierarchy does not simplify the data browsing on the client end.

If you have a case of a large number of databases with exactly the same measurements/point structure, you might be able to make a simpler layout by associating the EntityTypes with multiple measurements. (But at this point, wouldn't it make more sense to combine the databases on the InfluxDB side?)

If the goal is to reduce the number of options shown to users, perhaps a better solution would be to set `autogenerate = no` in your `.conf` file and hand-edit the `generated.xml` file to only include the desired measurements. This could be made simpler by adding a nice `whitelist` or `blacklist` option to the `.conf` file.

**Comment by srp-synengco** [comment]
Thanks for that, yeah I wasn't too sure about how entities usually are mapped in odata for consumption, but I think I get it a bit better now. So I'm happy to take these lessons, close this off and come back if the number of entities is getting unwieldy and we want a better way to trim it down, but for now, that's not a pressing issue for us
