### ISSUE TITLE
We're trying to integrate InfluxDB with Power BI. Do the errors we're seeing mean OData v3 / v4 is required?

### ISSUE THREAD

**Issue by mkarlesky** [Synergetic-Engineering/odata-influxdb#8]
Technically this is a question more than an issue and more to the development team than to the project. I couldn't find a great way to submit this other than as an issue.

My organization is working with InfluxDB for time-series sensor data. It's been great thus far. We're also using Microsoft's Power BI tool for some of our analytics. Power BI does not natively support InfluxDB†, but it can work with a handful of generic data access formats including OData.

We were thrilled to find your odata-influxdb project. Yesterday I set up an Influx instance, Power BI, and your odata-influxdb project. Everything was going along pretty well until I discovered that the pyslet project only support OData v2, and Power BI only works with OData v3 / v4.

We are newbies at best in working with OData. Given that you have successfully wired up InfluxDB as an OData feed, we consider you something of domain experts. According to the developers, the pyslet project will not be supporting OData v3 for a while yet. Do you have any suggestions on pulling together more recent OData version support for InfluxDB? That is, what projects or starting points would you point us to in order to build that support as easily as possible? Would it be possible to patch onto your project some sort of translation from OData v2 to v3?

Thanks in advance for anything you can suggest.

† We've learned that Microsoft now has native InfluxDB support in their internal development schedule for Power BI. We just don't know when it will be available. It seems likely they will provide it as there's growing interest in supporting Influx. We're just trying to figure out a stopgap between then and now.

**Comment by srp-synengco** [comment]
Thanks for the feedback @mkarlesky, good to hear that this project could be useful beyond our team

We are definitely interested in progressing this forwards, @soundstripe is the brains behind it, so I'll let him comment on your ideas

Out of interest, what features in Power BI don't work with OData v2? I've been doing some basic dashboarding in Power BI using this tool without any issue, but I'm somewhat new to these two technologies, so am by no means using an overly advanced influx database, nor am I doing anything particularly advanced in Power BI. So I'm keen to learn the limitations

**Comment by soundstripe** [comment]
I'm interested to know what doesn't work, as well. I have a limited set of test data. As far as I can tell, OData v2 and v3 are fairly compatible -- clients (like PowerBI) that speak v3 should be able to talk to v2 servers for the most part.

I based this on pyslet because it seemed the most feature-complete OData implementation available in Python. It would be a pretty major undertaking to add OData v4 features to it.

**Comment by mkarlesky** [comment]
Thank you so much for the prompt reply. And thank you for the project. If you're using your own project with Power BI then I think it's our inexperience with OData that is the essential problem and not the OData version issue after all.

We tried all manner of URLs to set up our Influx instance as an OData feed in Power BI and only managed to get error messages. When we fed in the metadata URL we just saw Power BI present a giant XML blob. Experimenting with a web browser as well as hitting our odata-influxdb instance port directly with telnet all produced things that looked appropriate. We just didn't quite grasp what to provide Power BI when it asked for the base URL.

I'll admit ignorance and simply start with asking: What is the appropriate URL to provide Power BI when connecting to an odata-influxdb instance? `http://<host>:<port>/` gave errors. `http://<host>:<port>/$metadata` produced the XML blob that Power BI didn't seem to know what to do with. Variations of URLs ending with `InfluxDB`, `InfluxDBSchema`, and educated guesses at OData URLs for the entities within our testing database produced more errors.

A super brief tutorial on OData+Power BI and/or a recommendation on a good OData URL explainer is probably all we need here.

Thank you again.

**Comment by soundstripe** [comment]
`http://<host>:<port>/` should be the correct OData endpoint URL.

Did you get a traceback on the server-side when PowerBI hit the server?

**Comment by mkarlesky** [comment]
I just tried this. In fact, no. There's no traceback when Power BI hits our odata-influxdb instance. However, if we provide the URL `http://<host>:<port>/$metadata` to Power BI we do see our metadata in the resulting query editor (full of XML text) — but again no traceback.

If we hit `http://<host>:<port>/` with a web browser, we see a traceback (snipped below).

```
⚡ python server.py
INFO:odata-influxdb:Generating OData metadata xml file from InfluxDB metadata
WARNING:root:Bad attribute value for ('~', u'Name'): farmlab__Air Temperature
WARNING:root:Bad attribute value for ('~', u'Name'): farmlab__Air Temperature
ERROR:root:EntitySet Default has undeclared type: InfluxDBSchema.farmlab__Air Temperature
INFO:odata-influxdb:Starting HTTP server on port 9999...
c-50-175-78-119.hsd1.tx.comcast.net - - [07/May/2017 19:40:03] "GET / HTTP/1.1" 200 2182
c-50-175-78-119.hsd1.tx.comcast.net - - [07/May/2017 19:40:14] "GET / HTTP/1.1" 200 2182
c-50-175-78-119.hsd1.tx.comcast.net - - [07/May/2017 19:40:16] "GET /$metadata/InfluxDB HTTP/1.1" 400 236
c-50-175-78-119.hsd1.tx.comcast.net - - [07/May/2017 19:40:18] "GET /$metadata HTTP/1.1" 200 91777


```

**Comment by soundstripe** [comment]
Looks like I forgot to account for spaces in measurement names. OData doesn't allow spaces where that is. I can fix that...actually part of that change is trivial but there's more to it. I'll take a look.

**Comment by mkarlesky** [comment]
Fantastic. I am very happy to try that out when it's ready (and it's daytime work hours in this part of the world again). Thank you again.

**Comment by srp-synengco** [comment]
thanks @soundstripe, i merged in #10 (hopefully not prematurely) as the fix to this / #9 - keen to see how it goes on your db @mkarlesky

**Comment by mkarlesky** [comment]
@srp-synengco Tried it out and dropped our results as a comment in #9.

If the team sees fit, feel free to close or otherwise organize this question thread appropriately. Given that your use case matches ours I think the original question is no longer relevant. Further, from the progress we're seeing in addressing the space problem, I think our experience folds into your existing development and retiring of bugs and feature requests.

**Comment by srp-synengco** [comment]
Yeah, thanks for the testing and feedback @mkarlesky, it's definitely useful to capture some of these edge cases before we run into them on our side
